name: spacebots
region: ams
services:
    - github:
          branch: main
          deploy_on_push: true
          repo: Longwelwind/space-bots
      http_port: 8080
      name: api
      run_command: npm run start
      source_dir: /
      envs:
          - key: DATABASE_HOSTNAME
            scope: RUN_TIME
            value: ${main.HOSTNAME}
          - key: DATABASE_USERNAME
            scope: RUN_TIME
            value: ${main.USERNAME}
          - key: DATABASE_PASSWORD
            scope: RUN_TIME
            value: ${main.PASSWORD}
          - key: DATABASE_DATABASE
            scope: RUN_TIME
            value: ${main.DATABASE}
          - key: DATABASE_PORT
            scope: RUN_TIME
            value: ${main.PORT}
          - key: CACERT
            scope: RUN_TIME
            value: ${main.CA_CERT}
          - key: FIREBASE_API_TOKEN
            scope: RUN_AND_BUILD_TIME
            type: SECRET
            value: EV[1:uq2rxF5+fJZs8v1MgaCrxmqifcuKgUV8:n6TQsmnqAlyQBaoYHC5V9px3WVwFLcYHpXrdutIZDVc9ghURcpGgf6O52Cgjy6ReyFVEhkLw5KTnP8+ZuGNdW0K8jQ1iqrPGTNm46HchlfNHqEznRJyDziDwJwSenb2IdO54f9NuFKVS23py8u8vNQCgG72pVCVm1A5dTcCipPHQqpjAji2J6cyeDvIDIlpuT3xTMDHekBch/XQQY1xaU4PTyeY9UxJ+hT5fBK0DFNrFT97lGaE6D8ZXDF2ab+zMvSZPv3/6GBciZdiq2EEjv4fxwmWnjaduUtGn1YuLyocnEc4DqrJcdWCg3GDAmpOEv7PygqwbyW66NtEvcGKOy1qR9k1D+jn/SeU2WsDzFIGkvrf7EIV1NrcZ4LqAzaSLvx/l7ZKn6Rm8E1DDDqsaklTdBeiHvtM8EGRW9fS5uOWoBTLiVPVpDGMsz3p1iOEZiADFiq0vWKQbmQxEmEiGkv0xU+4JE/DIVI9PvjimIOm5u48HQspH+8h46D0l7pWCryELy0PTiRBe5ajQrpnT3wUnByKgyvce2O0rKxlKM9BQO0OZ5NuvR+LUrdtVdCVQbzT8DjxG1ZrEImmqtT+XnKdoeMd1tEf/PvWWzcx/3Rjql3N3AXQlS+Ex9NAMdncM8hc5Ll9WBMt+6Ixg64FOVgS5MIxoeyMViiVlKopSobr54kqG7qIX7MznMVFJ4oxklq4nwITG1XAFEw/IvKnJrlPE9MavgqjHSi0ffDNqdA23II2Rmqyin7uuYUZYWplb6co9WDTt/iJXQrqrGg2ZapE9QBs7qemAEywn3Jo+MzvY18E0uEp6unNVxdfHnZo+6v5/3wTv2K4AjuHIrcwbXpWFaY5cXbXAldfvSpXsfrU7/55EUyL5UM2bcQydIFcUrQqbx4EDskbXj1z+pBdgyf9x/sGo7HhL4TZsn3yT6sdC1dbqLKKYb6pvgqVJ5zJexXVel72a/2RrbWB+3YZfT3T8Xj17xFS4qpitSpbZPZRru7sDQ80jup/9oXS/UL7Y61DRQ+jTFusqVpUM5xwBcQ2eqoPtfrGwGR+iAbTJk4UVl6GAzFW3Iv8kk8/QmN5ijxFtRQGLzS7L10so/XTb7KIMi0lSdQD8SfWdMzISFCex//SyDdl6ZUAMDZS1vol3P9ePYtEsyVo4DtzTkMTBdLsLF/5vwoWLE1el6WPOYp+nV0ebJJ3q4urLvRmjcSH7kCfIZ1ef2FCNXp9lDfmV5cnVVks2JSchdnPC4DGh9aPQfpdEzwN15GFbrpur2PkHgGo4Ov7ohP0g9vlS2XsT3QMcExxBlcqSeIchMEj1Ofo7k61Otza8rdCNMzhSIADjUu2h4IjyLA9QEKlApDThcoQUEni6ghfZDzFgCIxF5ykJwwK1jsgKV9KJF4BvKg/6y42s1LU3RkPE5YQ81czP+WwrXBLwpWTWJlo13THoKjr5q57ecs/2hqFTLrBhGMQa6Zh3MCKI3K9SoRVpHtyXsZWgOBPeyGA03DRjFuNeWDr6HgscyWXWr6WJ1A2VooBYFY1AVUBjsH19ehaIB0VxuWD4/KeP4zZ8VZpkOErBGU7l25Hte7mosrsyYPjSnsGqtUTEafbhesAsKMIyoArnd2BwhIiBu/BBXt8U2MBOkBaVColsdOZTJjkJqP+1waRAUNt1wh0IAl1i7dJd+LhvBemYNJ8XoOH4FgaYqIUz+o/Vw5WVUAo2JzYfp7/0vYjqyh1FdjX6nYTHRlLnEDwNON7GgHkI1jvyr6WAMuES5jc30addhN8ZKi97IXDRc0vCSUTcAqKlJmbc5Dhs4VOaekuiYGulv8gXWLcuR5YPdkGVW1yUxGnot0VrL3bjDkb/8Jg/IaG39SHs4MRX3Sc2bjmXbkm56h36s+qwtQ4vv48nEmtcajY2DR5LqUgnNcva4ORHgvJpFzR7cqeUvXOZxMwDiyJMJ2uaK7+fLD5H+kdrzoAbxejdZ7IkJgg3cQPBtNTseZZAArnrbKApnJoiQ5naYDaIbs3eAQyW8qiptTZQBHFTY+PJQeBdnZzCT8kIP1v2AwEQKL/EaOPaKemsQ2NqrcMnQLIWBz68iYkFykyM4ek1bEAhq7dhctsRuWRA/XyJ6xPFfIpszyxkEwTD4fYWuF2tZ1tJr1o9jzrgdzICjjEk2YdUQoGoEuvSVBC8rSt6yc9DAAcfW9abS0qgn9aRcx75xsNj22FRu8NTCMUsA1qwt2P/rQk/JVKWhKsB3HmlBEf7qssvG+KY7+UFTPdu6xCamGe7J9zlMoeTm7owK2DNSFvEAQTNBrs5yVRfTzVEfEAkp/1zHLoAfMJFZPfNwo22FmQdmg9Bol8Hr5cuQ+QusIV7/3dn8tbf/YvTxA6ab7/SrliULWWajK9MVJph8L+8yvcaqwQbOgNJdDGZhldgCPqGG82PUDcX3RXo2pPpji2qo3SR3qoUz7aydzF8shaP0jn+IdBb27XNxnY8lQrSvDmgoP1sDKAM2LwMntqPT8ceryKNKmLBgJNsbYGwmHdkSeBF57JgsX1R8uf3ypPMfJT3eFaDjyiank4cb3FIMc0BmvwVSulnSa1uRV/3bykvigPFS2KjT0VKr1wS1bcsT0SDlk2iu6fqWRKzKfuEoOAge4R/ofg/fMIjhswAQQQcaRTOyk6Tlkz5k37Xvf7AHEbfmU0JnwL+2GJWL619L6Sf9oRapeILNS+kPWzmEpgkb4gRy4Os9GxxjuuQoiXP+e8R6l2gTpTwbJxNXN2uUraipz3ucfY1qKaKGGeaQ+EbQWxXcj3FAw8xteY2xRUW+it/vKqW7p6+hduOBj8t8WwbanLyZp0H+7t63V7fNRkDEVu+/lYXjcjuIo9Mo0qGp5L36a6AM3geiEu1+jUiAh74/YndVv+oRATv1Nml5e+n0UsFKokaH26FeafwTCwB7gTwhS9tX1C170Uy9HE1id2ij+M4mxEZ5f+bqYUBvtFs8zXegJ0xlJlphnYdd6D5XDw1o/hHnq+RUvrAMG4lQ7pU0M5+KYaqShS+Px79J4yI/+/l0QIFEJq5Mh0AOrxPzYpx35ox9g4/YIzj0f2sKuybV0mQVFGjWyZ3HKSQfBUnTrew61dA7c9XEiZvreYKD4lM6CzATiM3OP0ePN3x18g7lJxU9vXxVo7AVx8=]
          - key: DATADOG_API_KEY
            scope: RUN_AND_BUILD_TIME
            type: SECRET
            value: EV[1:qATfNEHGJdqxvx5vsIc37h2XvhkP2YwG:xJreB5GR3NQ/vOoJ8y2cfrHHbVope9febfLLHHMeMBUp80LMgiT6B5qL6Q32qazQNoZRrtq5uN0=]
      instance_count: 1
      instance_size_slug: basic-xxs
jobs:
    - name: migrate-database
      github:
          branch: main
          deploy_on_push: true
          repo: Longwelwind/space-bots
      run_command: npm run db-sync && npm run seed-prod-data
      instance_size_slug: basic-xxs
      envs:
          - key: DATABASE_HOSTNAME
            scope: RUN_TIME
            value: ${main.HOSTNAME}
          - key: DATABASE_USERNAME
            scope: RUN_TIME
            value: ${main.USERNAME}
          - key: DATABASE_PASSWORD
            scope: RUN_TIME
            value: ${main.PASSWORD}
          - key: DATABASE_DATABASE
            scope: RUN_TIME
            value: ${main.DATABASE}
          - key: DATABASE_PORT
            scope: RUN_TIME
            value: ${main.PORT}
          - key: CACERT
            scope: RUN_TIME
            value: ${main.CA_CERT}
databases:
    - name: main
      engine: PG
      version: "12"
domains:
    - domain: space-bots.longwelwind.net
      type: PRIMARY
ingress:
    rules:
        - component:
              name: api
          match:
              path:
                  prefix: /
